substitutions:

  light_entity_1: "light.aanrecht_2"
  light_entity_2: "light.eethoek"
  light_entity_3: "light.woonkamer"
  light_entity_4: "light.alle_lampen_in_huis"

  light_widget_name_1: "Aanrecht"
  light_widget_name_2: "Eethoek"
  light_widget_name_3: "Woonkamer"
  light_widget_name_4: "Allelampen"


  light_label_name_1: "spotlights 1"
  light_label_name_2: "ceiling lamp"
  light_label_name_3: "night lamp"
  light_label_name_4: "pendant lamp"

packages:
  light_panel: !include lights_panel.yaml

  light_1: !include
    file: light_rgb_widget.yaml
    vars:
      light_entity: "${light_entity_1}"
      widget_name: "${light_widget_name_1}"
      
  light_2: !include
    file: light_rgb_widget_slider.yaml
    vars:
      light_entity: "${light_entity_2}"
      widget_name: "${light_widget_name_2}"
      
  light_3: !include
    file: light_temp_color_widget.yaml
    vars:
      light_entity: "${light_entity_3}"
      widget_name: "${light_widget_name_3}"

  light_4: !include
    file: light_brightness_widget.yaml
    vars:
      light_entity: "${light_entity_4}"
      widget_name: "${light_widget_name_4}"


