substitutions:

  shutter_entity_1: "cover.zonnescherm"

  shutter_widget_name_1: "Zonnescherm"


  shutter_label_name_1: "ZonneschermAchtertuin"


packages:
  shutter_panel: !include shutter_panel.yaml

  shutter_1: !include
    file: shutter_widget.yaml
    vars:
      shutter_entity: "${shutter_entity_1}"
      shutter_widget_name: "${shutter_widget_name_1}"